### PR TITLE
add edrixs

### PR DESCRIPTION
**Pull request by mpmdean**
It would be great to include EDRIXS if feasible.

### CODE REVIEW

**Comment by mpmdean** [comment]
Maybe this can be merged now?

**Comment by danielballan** [comment]
Oops, this notification got buried. Will deploy today.

**Comment by danielballan** [comment]
Deployed in the "Scientific Python (beta software environment)". Will deploy to "Scientific Python" in a day or so if there are no issues.

**Comment by mpmdean** [comment]
Should this have deployed to the "Scientific Python" kernel?

**Pull request merged**
