### PR TITLE
MNT: temporarily pin numpy back to unbreak modestimage

### PR DESCRIPTION
**Pull request by tacaswell**
working on fixing modest image, short-term fix.

### CODE REVIEW

**Review by XYangXRay — APPROVED** [review]
regular numpy version update. everything seems good.

**Review by mrakitin — CHANGES_REQUESTED** [review]
This may not be needed. Instead, you could add a minimum pin for the `modestimage` package as `>=0.2=*_2` as it was just published to https://anaconda.org/conda-forge/modestimage/files (based on https://github.com/conda-forge/modestimage-feedstock/pull/4) to ensure the version with the fix is selected.

**Comment by tacaswell** [comment]
I agree, was not sure which would be faster (getting the package rebuilt with the patch or this approach).

I think now that a patched modestimage is available we just need to rebuild the image?

**Comment by tacaswell** [comment]
We should not need to pin as https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/466 and https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/465 should patch CF's metadata so that the existing modestimage builds claim to have an upper bound on of np < 1.24

**Pull request closed without merging**
